### ISSUE TITLE
Index out of range exception while parsing subcommand

### ISSUE THREAD

**Issue by kahlkevin** [dotnet/command-line-api#1473] opened 2021-11-18 10:02 UTC
Compile this simple .NET 6 C# sample:
```csharp
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;

var testCommand = new Command("test", "test mode")
    {
        new Argument<FileInfo>("required-file").ExistingOnly(),
        new Argument<FileInfo>("optional-file") { Arity = ArgumentArity.ZeroOrOne }.ExistingOnly(),
    };

var rootCommand = new RootCommand() { testCommand };

var builder = new CommandLineBuilder(rootCommand).UseDefaults();

return builder.Build().Invoke(args);
```
**Repro:**

0. Using package / version: `<PackageReference Include="System.CommandLine" Version="2.0.0-beta1.21308.1" />`
1. Invoke: `sample.exe test foo`

**Result:**

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.CommandLine.Binding.ArgumentConverter.TryConvertArgument(ArgumentResult argumentResult, Object& value)
   at System.CommandLine.Parsing.ArgumentResult.Convert(IArgument argument)
   at System.CommandLine.Parsing.ArgumentResult.GetArgumentConversionResult()
   at System.CommandLine.Parsing.ParseResultVisitor.ValidateAndConvertArgumentResult(ArgumentResult argumentResult)
   at System.CommandLine.Parsing.ParseResultVisitor.Stop(SyntaxNode node)
   at System.CommandLine.Parsing.SyntaxVisitor.Visit(SyntaxNode node)
   at System.CommandLine.Parsing.Parser.Parse(IReadOnlyList`1 arguments, String rawInput)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at Program.<Main>$(String[] args) in C:\path\to\Sample.cs:line 18
```

**Comment by elgonzo** [comment] 2021-11-18 12:38
Seems to be a duplicate of https://github.com/dotnet/command-line-api/issues/1395

**Comment by kahlkevin** [comment] 2021-11-19 02:04
> Seems to be a duplicate of #1395

Agreed. How can I tell which commits are included in the version I'm running? There aren't any Tags/Releases newer than April 2021 (v2.0.0-beta1.21216.1) showing in the public repo, yet newer packages have obviously been published to nuget feed...

**Comment by jonsequitur** [comment] 2021-12-02 00:53
We plan to have an update within a week. It will contain a fairly significant number of changes.

**Closed** 2021-12-02 03:53 UTC
Labels: bug, duplicate
