### ISSUE TITLE
Option of leaf command gets value of parent command argument if option name starts with argument name

### ISSUE THREAD

**Issue by greijner** [dotnet/command-line-api#1480] opened 2021-11-23 08:54 UTC
If a parent command has an argument with a particular name (e.g. `portal`) and a child command has an option with a name that starts with the name of the argument of the parent command (e.g. `--port`), then if the `--port` option is bound to the same value as the `portal` argument. This only happens if the `--port` option is not provided.

A code sample to demonstrate this is shown below:
```
class Program
{
    static int Main(string[] args)
    {
        var serviceCommand = new Command("service", "A portal service")
        {
            new Option<int?>("--port", "The port of the service")
        };

        serviceCommand.Handler = CommandHandler.Create<int, int?, InvocationContext>(TcpClientHandler);

        var command = new RootCommand("Control portal")
        {
            new Argument<int>("portal", "Portal ID")
        };

        command.AddCommand(serviceCommand);

        return command.Invoke(args);
    }

    private static void TcpClientHandler(int portal, int? port, InvocationContext context)
    {
        context.Console.Out.Write("Portal: " + portal);
        context.Console.Out.WriteLine();

        context.Console.Out.Write("Port: " + port);
        context.Console.Out.WriteLine();
    }
}
```

The following is written to the console if this program is invoked with the command line args `13 service`

```
Portal: 13
Port: 13
```

Adding the following code to the handler fixes this, but I think that this is a bug that can be fixed.
```
if (!context.ParseResult.Tokens.Any(x => x.Type == TokenType.Option && x.Value == "--port"))
    port = null;
```

**Comment by elgonzo** [comment] 2021-11-23 09:54
Testing against the daily build 2.0.0-beta1.21568.1 (from the [daily builds nuget feed](https://github.com/dotnet/command-line-api#packages)), the observed behavior has changed, not confusing the _port_ and _portal_ method parameters anymore. Output with 2.0.0-beta1.21568.1 is:
```
Portal: 13
Port:
```
(The most current version on the official nuget feed 2.0.0-beta1.21308.1 still exhibits this issue, so this issue got fixed after publicizing 2.0.0-beta1.21308.1)

**Comment by jonsequitur** [comment] 2021-11-23 19:09
I believe this is a duplicate of #1434.

**Comment by DumboJet** [comment] 2021-12-01 10:07
This issue description helped me figure out how this library works more than the docs.
Although, I still don't understand what difference "Argument<T>" has compared to "Option<T>".

Also, from what I can tell, the options are injected to the handler based on the handler argument names?
Isn't that risky?
E.g. any rename on variables could break the code.
I would expect something like this:

	class Program
	{
		static int Main(string[] args)
		{
			var portOption = new Option<int?>("--port", "The port of the service")
				.AddAlias("-p")
				.AllowMultiple(false); // Allow chaining methods...
			var portalArgument = new Argument<int>("portal", "Portal ID");
			var serviceCommand = new Command("service", "A portal service")
			{
				portOption,
			};
			serviceCommand.Handler = CommandHandler.Create(TcpClientHandler, portalArgument, portOption); // Manually map options/arguments to handler arguments (based on order of appearance)... CommandHandler.Create(Action<T1, T2,...>, params IOption[] options>)

			var rootCommand = new RootCommand("Control portal")
			{
				portalArgument,
			};
			rootCommand.AddCommand(serviceCommand);

			return rootCommand.Invoke(args);
		}

		private static void TcpClientHandler(int portal, int? port, InvocationContext context)
		{
			context.Console.Out.WriteLine("Portal: " + portal);
			context.Console.Out.WriteLine("Port: " + port);
		}
	}

Focus on the labels "Allow chaining methods" and "Manually map options/arguments to handler arguments".

**Comment by jonsequitur** [comment] 2021-12-01 16:48
> Also, from what I can tell, the options are injected to the handler based on the handler argument names?
Isn't that risky?

Yes, but it also makes for much more concise code. It's modeled after the model binding features of ASP.NET MVC but that turned out to be unintuitive for a lot of people. The name-based matching is being split out into a separate package for people who prefer the less verbose convention and this will eventually be superseded by a source generator  which will avoid the kind of risk you're pointing out as well as be more performant.

Another approach you can use if you don't want to write the boilerplate `ParseResult` access code is this:

```csharp
static class Program
{
    private static Option<int> _opt;

    static int Main(string[] args)
    {
        _opt = new Option<int>("--port", "The port of the service");
        var serviceCommand = new Command("sync", "A portal service")
        {
            _opt
        };
        serviceCommand.Handler = CommandHandler.Create<int>(_opt, TcpClientHandler);

        var command = new RootCommand("Root");
        command.AddCommand(serviceCommand);
        return command.Invoke(args);
    }

    private static void TcpClientHandler(int value)
    {
        context.Console.Out.Write("port: " + val);
    }
}
```

**Comment by jonsequitur** [comment] 2021-12-01 16:51
I'm going to close this as it's a duplicate and has been fixed.

**Closed by jonsequitur** 2021-12-01 16:51 UTC
Labels: bug, duplicate
