### ISSUE TITLE
Parsing two list arguments doesn't work

### ISSUE THREAD

**Issue by mmierzwa11** [dotnet/command-line-api#584] opened 2019-07-08 11:25 UTC
```
                var argument1 = new Argument<List<string>>
                { Name = "arg1" };
                var argument2 = new Argument<List<string>>
                { Name = "arg2" };
                var command = new Command("do-stuff");
                command.AddArgument(argument1);
                command.AddArgument(argument2);
                command.Handler = CommandHandler.Create( (List<string> arg1, List<string> arg2) =>
                {
                    //TODO: Implement command handler
                });
                var builder = new CommandLineBuilder()
                    .AddCommand(command)
                    .UseDefaults();

                Parser parser = builder.Build();
```

Invoking following command definition as `"do-stuff args1 args2"` results in arg1 with both values and arg2 as null in CommandHandler - I expected args1 in arg1 list and args2 in arg2 list, is there any option to specify that spaces are delimiters for arguments and let say commas for items in list so invoking `"do-stuff args1a,args1b args2"` result in arg1 list with two items (args1a, args1b) and arg2 list with only one item (args2).

**Comment by jonsequitur** [comment] 2019-07-09 16:08
What you're seeing is the default behavior because `argument1` has no upper limit specified for its arity. You can see an example of how this works here: https://github.com/dotnet/command-line-api/blob/9604cdfd8e277f346df63077c712af7d99cff030/src/System.CommandLine.Tests/ParserTests.MultipleArguments.cs#L25-L53

The comma approach is interesting. Do you have examples of command line interfaces using this convention in the way you're describing?

Related: #37

**Comment by amis92** [comment] 2019-07-17 11:15
I can't say anything about existing tools, but PowerShell uses commas for lists, and CLI-tool framework [PowerArgs](https://github.com/adamabdelhamed/PowerArgs) uses this notation as well.

**Comment by mmierzwa11** [comment] 2019-08-21 07:44
I don't really know/remember any wide used tools with such approach, but in past I used to use **argparse** lib for python, which has such concept.

**Comment by jonsequitur** [comment] 2019-12-11 18:58
I'm closing this as a duplicate of #37. Please feel free to reopen if there are details I'm missing.

**Closed by jonsequitur** 2019-12-11 18:58 UTC
