### ISSUE TITLE
Multiple value of Option

### ISSUE THREAD

**Issue by wojtpl2** [dotnet/command-line-api#383] opened 2019-01-22 09:40 UTC
I'm trying to switch [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) (https://github.com/dotnet/BenchmarkDotNet/issues/1016) to `System.CommandLine`. 

But I have one problem. Currently BenchmarkDotNet uses multiple value of argument e.g.:
`dotnet run -c Release -- --runtimes net472 netcoreapp2.1` 
or 
`--filter *ClassA* *ClassB*`

Currently `System.CommandLine` doesn't support this. When I configure option:
```c#
   Option Filter() => new Option(new[] { "-r", "--runtimes" },
        "Full target framework moniker for .NET Core and .NET. For Mono just 'Mono', for CoreRT just 'CoreRT'. First one will be marked as baseline!",
        new Argument<string[]>());
```
I have to repeat an alias for each parameter value, like this:
`--runtimes net472 --runtimes netcoreapp2.1`

The worst scenario, instead:
`--filter *ClassA* *ClassB* --runtimes net472 netcoreapp2.1 --exporters GitHub StackOverflow RPlot CSV JSON HTML XML --attribute Attribute1 Attribute2` 
we should type this:
`--filter *ClassA* --filter *ClassB* --runtimes net472 --runtimes netcoreapp2.1 --exporters GitHub --exporters StackOverflow --exporters RPlot --exporters CSV --exporters JSON --exporters HTML --exporters XML --attribute Attribute1 --attribute Attribute2`
This example doesn't contain other attributes that can have one value. 

There is unit test that shows it doesn't work https://github.com/dotnet/command-line-api/blob/4f3b654f9d7116004d6c3f98ec20bf19c14e967d/src/System.CommandLine.Tests/ParserTests.cs#L570-L578

**Comment by wojtpl2** [comment] 2019-01-22 11:39
If you would like to I can prepare PR which will change this behavior.

**Comment by jonsequitur** [comment] 2019-01-22 15:49
I believe this is a duplicate of #368 and (with the difference of the delimiting character) #37.

If you would like to prepare a PR that would be great. 

Just as a heads-up, this is related to #310.

**Comment by wojtpl2** [comment] 2019-01-22 17:24
It is not duplicate. I don't want to split value. I want to pass many values with space between them. It is default behaviour of CommandLineParser library.

**Comment by jonsequitur** [comment] 2019-01-22 17:43
> I don't want to split value. I want to pass many values with space between them. 

My understanding is that this is also the goal of #368. It has implications for both the parser (e.g. `myapp --opt a b c` parses `a`, `b`, and `c` as arguments to `--opt` assuming `--opt` has a minimum arity of at least 3), as well as for the binder (arguments `a`, `b`, and `c` can be bound to a single list parameter, e.g. `List<string>`).

Does this sound correct?

**Comment by wojtpl2** [comment] 2019-01-22 23:03
I make PR #384. if there is still  something to improve in this issue, please let me know.

**Comment by amis92** [comment] 2019-01-23 12:14
I think since #384 is merged, the issue can be closed?

**Closed** 2019-01-23 16:56 UTC
Labels: parser
