### ISSUE TITLE
Global Option IsRequired flag ignored.

### ISSUE THREAD

**Issue by kuhnboy** [dotnet/command-line-api#1574] opened 2022-01-11 01:35 UTC
System.Commandline (2.0.0-beta2.21617.1)

When I add a global option that is required, it is not required when executing a child command. Example:

```c#
using System.CommandLine;
using System.CommandLine.NamingConventionBinder;

public class Program
{
    public static async Task<int> Main(string[] args)
    {
        var rootCommand = new Command("widget");

        rootCommand.AddGlobalOption(new Option<string>("--device") { IsRequired = true });

        var childCommand = new Command("doodad") { Handler = CommandHandler.Create<string, CancellationToken>(ExcretePlumbus) };

        rootCommand.AddCommand(childCommand);

        return await rootCommand.InvokeAsync(args);
    }

    private static Task ExcretePlumbus(string device, CancellationToken cancellationToken)
    {
        Console.WriteLine($"{device}");

        return Task.CompletedTask;
    }
}
```

If I run with the arguments:

```
widget doodad
```

Device is not required even though it is marked with `IsRequired = true.`

**Comment by jonsequitur** [comment] 2022-01-11 01:52
This is a duplicate of #1540.

**Closed** 2022-01-11 01:52 UTC
