### ISSUE TITLE
No arguments should default to showing help

### ISSUE THREAD

**Issue by fhurta** [dotnet/command-line-api#828] opened 2020-03-22 18:24 UTC
Currently, the help is shown on any of "--help", "/h", etc but not in case there is no argument specified for the program on the command line.

I have RootCommand with no handler having two subcommands with respective handlers. The behavior when the app is launched with no arguments is that the program exits with code 0. No command performed, no help written.

Show the help also in case when there is no command specified (and there is some defined in the app) or provide help handler that could be explicitly set to "parent" commands (i.e. commands that have subcommands).

**Comment by jonsequitur** [comment] 2020-03-22 18:26
I believe this is a duplicate of #817, which has been fixed. Could you update to the latest version from the MyGet feed and confirm?

Thanks.

**Comment by fhurta** [comment] 2020-03-22 19:43
Ok, with the latest daily build it works. 
What is the plan to bring it to regular nuget package?
Thanks

**Closed** 2020-03-24 15:16 UTC
Labels: waiting-on-feedback
