### ISSUE TITLE
The Global Tool settings are not evaluated

### ISSUE THREAD

**Issue by changhuixu** [dotnet/command-line-api#682] opened 2019-11-19 02:43 UTC
I have a demo project for making a custom Global Tool. The `csproj` file looks like the following.
```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>stat</ToolCommandName>
    <PackageId>stat</PackageId>
    <PackageOutputPath>.nuget</PackageOutputPath>
  </PropertyGroup>
```
It works but there is a minor flaw. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/16184464/69111531-79c10180-0a43-11ea-8adb-7445982119bc.png)

The help message in the Console doesn't show the actual command that is set in the `csproj` file.
Could you take a look at this issue?
Thank you.

**Comment by jonsequitur** [comment] 2019-11-20 01:16
This is a duplicate of #403. The current workaround is here: https://github.com/dotnet/command-line-api/issues/403#issuecomment-501730840

**Closed by jonsequitur** 2019-11-20 01:16 UTC
Labels: duplicate

**Comment by changhuixu** [comment] 2019-11-20 02:11
Thank you @jonsequitur
