### ISSUE TITLE
Hang after waiting on a CancellationToken in a command

### ISSUE THREAD

**Issue by rengeln** [dotnet/command-line-api#2331] opened 2024-02-08 23:36 UTC
```
using System.CommandLine;

public class Program
{
    public static int Main(string[] args)
    {
        var cts = new CancellationTokenSource();
        Console.CancelKeyPress += (_, _) => 
        {
            Console.WriteLine("Ctrl+C pressed");
            cts.Cancel();
        };

        var rootCommand = new RootCommand();
        rootCommand.SetHandler(() => Foo(cts.Token));

        return rootCommand.Invoke(args);
    }

    public static void Foo(CancellationToken ct)
    {
        Console.WriteLine("In Foo()");
        ct.WaitHandle.WaitOne();
        Console.WriteLine("Cancelled");
    }
}
```

When you run the above app, then press ctrl+C, it will print `Cancelled`, but the app will never exit. The callstack is indecipherable to me I'm afraid, but it's within the invocation handler.

**Comment by elgonzo** [comment] 2024-02-09 00:06
_Disclaimer: I am only a user of the System.CommandLine library and not associated with the project or its authors/maintainers._

This behavior is not related to and not caused by the System.CommandLine library, as can easily proven by eliminating System.CommandLine from your code example:
```C#
public static int Main(string[] args)
{
    var cts = new CancellationTokenSource();
    Console.CancelKeyPress += (_, _) =>
    {
        Console.WriteLine("Ctrl+C pressed");
        cts.Cancel();
    };

    Foo(cts.Token);
}
```
Same effect: Program doesn't exit. (The same peculiar behavior also happens when replacing the CancellationTokenSource/CancellationToken with a simple ManualResetEvent/AutoResetEvent.

As this issue is not related to System.CommandLine, i'd suggest you close this issue here. Unfortunately i also don't know what causes this. It's however probably a good question for stackoverflow.com, though (Stackoverflow might perhaps even already have a similar question and answer(s) that might shine a light on this behavior...)

**Comment by elgonzo** [comment] 2024-02-09 00:33
Quick follow-up: It seems the issue is caused by your CancelKeyPress handler not cancelling the Ctrl+C request, which leads to initiation of process termination in response to Ctrl+C while also resuming the main thread (or something similar), which apparently at some point goes off the rails. I believe setting the `Cancel` property of the `ConsoleCancelEventArgs` instance passed to the CancelKeyPress handler to _true_ should resolve the issue.

**Closed** 2024-02-09 00:41 UTC

**Comment by elgonzo** [comment] 2024-02-09 16:41
@KalleOlaviNiemitalo,

i did once more a quick check, as your response made me start suspecting something. Like you, i did test on .NET 8 running as x64 process in Windows 11. However, i did the test from within VS2022, running it with VS' debugger. I did the test once more running both debug and release builds of the program _with_ and _without_ using the VS debugger. Running in the debugger, the program hangs in both debug and release builds. Running without the debugger, the program doesn't freeze. From my additional quick tests, it seems there is something going on with the debugger that leads to the program freezing.
