### ISSUE TITLE
Suggestions just don't work at all

### ISSUE THREAD

**Issue by lostllama** [dotnet/command-line-api#1121] opened 2020-12-09 08:09 UTC
I've followed the instructions [here](https://github.com/dotnet/command-line-api/blob/main/docs/dotnet-suggest.md) and installed `dotnet-suggest` as instructed. I've also added the contents of `dotnet-suggest-shim.ps1` to my PowerShell profile script (this didn't exist initially, so it's literally just the contents of `dotnet-suggest-shim.ps1`), and this can be seen when I execute `cat $profile`.

How I've tested suggestions:
1. I've downloaded the t-rex application from [here](https://github.com/jonsequitur/t-rex) and compiled it.
2. I navigate to the build folder with PowerShell, type `.\t-rex.exe --` and press <kbd>TAB</kbd>. Nothing appears.
3. I then try `c:\Users\Me\Source\Repos\TRex\bin\Debug\netcoreapp3.1\t-rex.exe --` press <kbd>TAB</kbd> and still nothing appears.

Is this feature just not ready yet?

`$PSVersionTable` reports that I'm using PowerShell version 5.1.18362.1171
My OS is Windows 10 Enterprise N
dotnet-suggest is version 1.1.142701+585298c3e5edb3c07cd55898225ec81dca8889f5

**Comment by lostllama** [comment] 2020-12-09 08:45
I've also built the t-rex application as a self-contained executable on Linux, and while it runs fine with `./t-rex`, it doesn't show any suggestions.

I've copied [this script](https://raw.githubusercontent.com/dotnet/command-line-api/main/src/System.CommandLine.Suggest/dotnet-suggest-shim.bash) into my `~/.bash_profile` file (again I didn't have this before and had to create it), and I'm using the same version of dotnet-suggest. I'm testing under WSL which appears to be running Ubuntu 18.04.1 LTS.

I've tried `./t-rex --` <kbd>TAB</kbd> and also `/tmp/t-rex/bin/Release/netcoreapp3.1/linux-x64/publish/t-rex --` <kbd>TAB</kbd> and this doesn't do anything.

**Comment by pieter-venter** [comment] 2020-12-09 15:50
Hi @lostllama , I recently went through a similar experience. It can confirm that suggestions are broken in the latest release on Nuget. There is one important [fix](https://github.com/dotnet/command-line-api/pull/1091) that you'll need for this to work, if you want to build locally. Latest main should be good. I believe a Nuget update is due soon if you just want to wait.

This [thread](https://github.com/dotnet/command-line-api/issues/1085) may also have some useful info on how to troubleshoot on Linux. Specifically this [section](https://github.com/dotnet/command-line-api/issues/1085#issuecomment-730583120).

FYI I added the script to my  ~/.bashrc file on Ubuntu. Also important that completions will only work once the command line app registers itself (first time your run it) _and_ your bash session has the script loaded. You can remove the sentinel file in the temp folder to force a registration next time you run it.

**Comment by jonsequitur** [comment] 2020-12-09 18:41
@lostllama Did you try installing `t-rex` from NuGet? https://www.nuget.org/packages/t-rex/ Local builds are known to have issues.

Another decent sanity check for suggestions is to try `dotnet-suggest` itself:

![dotnet-suggest-completions](https://user-images.githubusercontent.com/547415/101672690-0d78bd80-3a0b-11eb-92dc-f91a633fdcca.gif)

**Comment by lostllama** [comment] 2020-12-10 01:06
@jonsequitur 

> @lostllama Did you try installing `t-rex` from NuGet? https://www.nuget.org/packages/t-rex/ Local builds are known to have issues.

Unfortunately I was testing with t-rex because I can't get dotnet-suggest to work with my own project. I figured that if t-rex works, then it must be something wrong with my code.

> Another decent sanity check for suggestions is to try `dotnet-suggest` itself:

That's working fine by itself in both PowerShell and Bash.

**Comment by lostllama** [comment] 2020-12-10 01:10
@pieter-venter 

> Also important that completions will only work once the command line app registers itself (first time your run it)

Do I have to write some code to achieve this? I didn't see any in the t-rex code, so I didn't realise I needed to.

**Comment by jonsequitur** [comment] 2020-12-10 19:52
I don't believe the problem is with `t-rex` but with any local build.

**Comment by lostllama** [comment] 2020-12-10 23:17
@jonsequitur Assuming Pieter's linked issue and pull request is the solution, is there an ETA on when this will be available for public consumption?

**Comment by pieter-venter** [comment] 2020-12-11 02:36
@lostllama I may have given you the wrong info - I didn't realize a new Nuget package was published recently. However, I did quickly try create a small console app. I can confirm that it was registered correctly with `suggest` on Linux, but tabbing doesn't produce anything. I'd have to debug things more to figure out what's going wrong.

**Comment by jonsequitur** [comment] 2020-12-11 02:39
@pieter-venter We're having a package publishing issue at the moment so your fix isn't available yet on nuget.org.

**Comment by jonsequitur** [comment] 2020-12-11 21:56
The latest version of `dotnet-suggest` is now available on NuGet.org.

**Comment by ransagy** [comment] 2021-04-08 12:21
This still happens to me with a new `net5.0` console and the following dependencies/tools:

```
NET SDK 5.0.200
dotnet-suggest 1.1.161005+347d68d290165a5182489bb38fe6f0b18066e7e6
<PackageReference Include="System.CommandLine.DragonFruit" Version="0.3.0-alpha.21206.1" />
```

I can confirm dotnet-suggest completion itself does work.

**Comment by jonsequitur** [comment] 2021-12-08 02:14
I'm closing this as there's no clear repro, but I recognize that sometimes all of the moving parts don't come together. Please reopen if this is still an issue.

**Closed by jonsequitur** 2021-12-08 02:14 UTC
Labels: Area-Suggestions
