### ISSUE TITLE
Automatic binding of consecutive parameters to collection

### ISSUE THREAD

**Issue by Starkie** [dotnet/command-line-api#368] opened 2019-01-12 14:07 UTC
Some CLI programs infer that a list of consecutive parameters belong to the same option. For example, the program `cp` in unix has the following profile, were one or more `source` files can be specified to be copied to `directory`:

`cp [OPTION]... SOURCE... DIRECTORY`

The usage would be as following:

`cp file1 file2 directory`

I tried to implement a similar behaviour in a command line program, that receives a collection of paths:

```c#
static void Main(string[] paths)
{
  // Do something
}
```
I expected to invoke the program like this:
`dotnet run -- --paths file1 file2 file3`

But instead, the argument name had to be specified each time:
`dotnet run -- --paths file1 --paths file2 --paths file3`

Does a way to implement options with a similar behaviour exist? 

Might be related to #310.

**Comment by Starkie** [comment] 2019-01-14 11:31
> #310 will allow command arguments to differ by type, name, and arity, so in your first example, the cp command would accept an `Argument<FileInfo[]> `and a second `Argument<DirectoryInfo>`.

I'm not sure I understand correctly this part. Does this mean that both types could match to the same `--paths` argument in the same command invocation? Or would that be the same command with a different "profile"?

I'll check the workaround you provided when I get the time. Is there something similar for the DragonFruit model? It's the one we are currently using.

> Do you have any examples where you would expect the option arguments to similarly be able to differ by type?

In my use case, no. The inputs of the argument are all of the same type.

In any case, here's the link of the PR I'm working on. https://github.com/Starkie/DuplicateExtensionFinder/pull/1

**Comment by Starkie** [comment] 2019-01-15 08:57
Oh, sorry for the confussion: In my C# example I didn't specify the `target_dir` that I mentioned in cp. 😅 
But yes, I think that would be a valid model to represent this command.

**Comment by jonsequitur** [comment] 2019-03-21 14:18
I'm closing this as I believe it's a duplicate of #310. Please reopen if you think I might be overlooking some detail.

**Closed by jonsequitur** 2019-03-21 14:18 UTC
Labels: parser
