### ISSUE TITLE
HelpBuilder Fails In UWP Project

### ISSUE THREAD

**Issue by adamhewitt627** [dotnet/command-line-api#642] opened 2019-09-13 07:10 UTC
I was recently adding support for `appExecutionAlias` to a windowed UWP app, and wanted to include some additional parameters. Trying to include `--help` through `UseDefaults` throws an error: `System.IO.IOException: 'The handle is invalid'` 

**Version**: `0.3.0-alpha.19405.1`

#### Reproduction
[CommandLineUWP.zip](https://github.com/dotnet/command-line-api/files/3608729/CommandLineUWP.zip)
1. Open in Visual Studio.
2. Run the debugger (with or without `Do not launch, but debug my code when it starts` enabled)
3. From a command line, execute: `clrepro --help`. (This will trigger the parser whether the app is running or not, hence why number 2 doesn't matter)

#### Stack Trace
```log
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at System.CommandLine.HelpBuilder..ctor(IConsole console, Nullable`1 columnGutter, Nullable`1 indentationSize, Nullable`1 maxWidth)
   at System.CommandLine.CommandLineConfiguration.<>c.<get_HelpBuilderFactory>b__22_0(BindingContext context)
   at System.CommandLine.Invocation.ServiceProvider.GetService(Type serviceType)
   at System.CommandLine.Binding.BindingContext.get_HelpBuilder()
   at System.CommandLine.Invocation.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetResultCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at CommandLineUWP.App.OnActivated(IActivatedEventArgs args) in C:\Users\adamh\Source\repos\CommandLineUWP\App.xaml.cs:line 26
```

**Comment by wiredprairie** [comment] 2019-09-13 15:33
I've had this error occur in a .NET Core Console app as well (ver 2.2.103), debugging/running within Visual Studio Code.

I could reproduce the error in C# with my app by doing just this:
```
Console.WriteLine($"{Console.WindowWidth}");
```
For my app, I was able to change the `console` configuration in `launch.json`:

```
	"console": "integratedTerminal",
	// "console": "internalConsole",  << this setting causes the error
```
I don't know however if there are any adjustments you can make that are similar for Visual Studio and your UWP app.

**Comment by adamhewitt627** [comment] 2019-09-13 15:41
[These remarks ](https://docs.microsoft.com/en-us/dotnet/api/system.console.windowwidth?view=netframework-4.8#remarks) are regarding the setter, but it would stand to reason that they would apply to the getter as well. If output is redirected, "width" is less obvious.

**Comment by adamralph** [comment] 2019-10-20 15:55
This also occurs on build servers, at least when the OS is Windows.

**Comment by adamralph** [comment] 2019-10-20 16:08
This looks like a dup of https://github.com/dotnet/command-line-api/issues/599, which was fixed in https://github.com/dotnet/command-line-api/pull/611.

**Closed** 2021-03-18 23:25 UTC
Labels: bug
