### ISSUE TITLE
Can root commands handle global options?

### ISSUE THREAD

**Issue by N-Onorato** [dotnet/command-line-api#1117] opened 2020-12-06 22:48 UTC
Apologies if this is an inappropriate question/place to ask for assistance. 

Is it possible to define a option that wraps sub-commands? For example, say I wanted to print "Welcome to the pizza shop!" before executing any sub-commands if a user provides the option `-g` but I don't want the sub-commands to be aware of the `-g` option.

For example...
```C#
using System;
using System.CommandLine;
using System.CommandLine.Invocation;

namespace Example
{
    class Program
    {
        static void Main(string[] args)
        {
            var root = new RootCommand("Does Stuff");
            root.AddGlobalOption(new Option("-g", "gives you a nice greeting"));


            root.Handler = CommandHandler.Create((InvocationContext context) =>
            {
                if (context.ParseResult.ValueForOption<bool>("-g"))
                {
                    Console.WriteLine("Welcome to the pizza shop!");
                }
            });


            var pizzaCommand = new Command("pizza", "makes a delicious pizza.");
            pizzaCommand.Handler = CommandHandler.Create(() =>
            {
                Console.WriteLine("Making the Dough.");
                Console.WriteLine("Adding the Toppings.");
                Console.WriteLine("Baking the Pizza.");
                Console.WriteLine("Serving the Pizza");
            });
            root.AddCommand(pizzaCommand);


            root.InvokeAsync(args).Wait();
        }
    }
}
```

In this example the only way to print the greeting would be something llike `dotnet run -g` whereas the intention is for it to work for either `dotnet run pizza -g` or `dotnet run -g pizza`.

Also while I'm sure there are a lot of plans for the documentation, global options as a concept could be added to the [Syntax-Concepts](https://github.com/dotnet/command-line-api/blob/main/docs/Syntax-Concepts-and-Parser.md) page.

**Comment by rsking** [comment] 2020-12-07 02:29
duplicate of #1041

**Closed** 2020-12-08 01:49 UTC

**Comment by sanchit1591** [comment] 2021-08-10 21:09
If I reproduce the code above, I still face the same issue

**Comment by elgonzo** [comment] 2021-08-11 10:03
Your problem is not related to the global option. The global option is a red herring.
The problem is rather your code having two command handlers, and your expectation of the two command handlers being invoked.

As the name "command handler" suggests, the handler is for a command, not for an option. So, if you invoke a command line containing the "pizza" command, then the "pizza" command handler will be invoked. That's what you are seeing happening.

The behavior observed here is pretty much the same as discussed here https://github.com/dotnet/command-line-api/issues/1274
